[package]
name = "rust_key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version="0.6.0", features = ["image", "debug"] }
json = "0.12.4"
ring = "0.16.20"
