[package]
name = "rust_key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.6.0"
log = "0.4.17"
ring = "0.16.20"
